kind: pipeline
type: docker
name: default

platform:
  arch: arm

steps:
- name: install
  image: node:12-alpine
  commands:
  - apk add --no-cache python make g++ git openssh-client vips-dev
  - npm set registry http://npm.home.local
  - npm config set unsafe-perm true
  - npm install
  - npx lerna bootstrap --concurrency 2 --no-ci

- name: build
  image: node:12-alpine
  commands:
  - npm run build

- name: test
  image: node:12-alpine
  commands:
  - npm run test

- name: notify
  image: sfelis/drone-email
  settings:
    from:
      from_secret: mail_from
    host:
      from_secret: mail_host
    port:
      from_secret: mail_port
    username:
      from_secret: mail_username
    password:
      from_secret: mail_password
  when:
    status:
    - failure
