kind: pipeline
type: docker
name: default

platform:
  arch: arm64

steps:
- name: install
  image: node:14-alpine
  commands:
  - npm set registry $NPM_REGISTRY
  - npm config set unsafe-perm true
  - node scripts/disable-dependency.js api-server
  - npm install
  - find node_modules/@ffprobe-installer -name ffprobe -exec chmod ugo+x {} \;
  environment:
    NPM_REGISTRY:
      from_secret: npm_registry

- name: build
  image: node:14-alpine
  commands:
  - npm run build -- --ignore @home-gallery/api-server

- name: test
  image: node:14-alpine
  commands:
  - npm run test -- --ignore @home-gallery/api-server

- name: test:e2e
  image: node:14-alpine
  commands:
  - apk add --no-cache git git-lfs perl
  - git clone $E2E_DATA_REPO ./data
  - npm run test:e2e
  environment:
    TZ: Europe/Berlin
    E2E_DATA_REPO:
      from_secret: e2e_data_repo
  when:
    branch:
    - master
    event:
    - push

- name: notify
  image: sfelis/drone-email
  settings:
    from:
      from_secret: mail_from
    host:
      from_secret: mail_host
    port:
      from_secret: mail_port
    username:
      from_secret: mail_username
    password:
      from_secret: mail_password
  when:
    status:
    - failure
