# DB for keeping track of sync status to improve effiency
state_db: /path/to/sync_state.db

# Where symlinks will be created
dest_root: ~/Pictures

# Quarantine for unwanted files (only used if a source enables it)
quarantine_root: ~/QuarantinedFiles

# Global lockfile and state DB

# Disable sync progress bar
disable_progress: true

# Global media extensions
media_ext:
  images: [jpg, jpeg, png, gif, webp, bmp, tiff]
  videos: [mp4, mov, mkv, avi, mpg, mpeg, webm]

# Nextcloud connection details (only needed if any source uses nextcloud_tag)
nextcloud:
  server_ip: htpp://ip_or_web_address
  username: user
  app_password: password

# -------------------------------------------------------------------
# Sources list (you can define any number of entries)
# -------------------------------------------------------------------
sources:

  # N.B!!! Do not use the source name 'timer' since this is already used by
  # the sync system to specify a complete run of all sources by the systemd
  # timer
  # 1. Example: Local folder that enforces media filtering AND quarantine
  # - name: A
  #   type: local
  #   path: /mnt/sources/A
  #   filter_media: true       # only sync images/videos
  #   quarantine: true         # move other files to quarantine

  # 2. Photo Archive
  - name: nextcloud_photos
    type: nextcloud_tag
    path: /local_external/for/Photos
    named_folder: photos # the Folder name specified within nextcloud ext storage setup
    tag: PhotoFrame
    filter_media: false  # Only sync specified media files. Non media files can then be optionally quarantined if enabled, otherwise ignored
    quarantine: false    # Path to move photos or videos to, when deleted from the photo frame
    dest_on_frame_deletion: null # When item is deleted from the dest, its assumed to have been deleted via the photoframe.
                                 # In this case, the file can optionally be moved from the source to this specified folder.
                                 # By default, the source file is not touched but the nextcloud tag will be removed

  # Public Upload Folder (Handled separately since this is the folder for photos from upload link, and there should be additional checks)
  - name: nextcloud_public_uploads
    type: nextcloud_tag
    tag: PublicUpload          # the Nextcloud tag to pull from
    path: /local_external/for/PublicUpload/Photos
    named_folder: PublicUpload/Uploaded
    filter_media: true         # Only sync specified media files. Non media files can then be optionally quarantined if enabled, otherwise ignored
    quarantine: true           # When active, files that are not images or videos are moved here during sync
    dest_on_frame_deletion: /local_external/for/PublicUpload/Removed  # Path to move photos or videos to, when deleted from the photo frame
